#----------------------------------------------------------------------
# This file was generated by /home/tom/Desktop/PythonToolkit/icons/ptk icons/Console/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

#-------------------------------------------------------------------------------
console48 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABHNCSVQICAgIfAhkiAAADGFJ"
    "REFUaIHtmXmMXdddxz/n3vvum/dms2fGnsXxNo6d4iVO6oJNk9CkTdpUiFJAbGIRlYhaQKoE"
    "/SviH4SCQvgjoqhIVaQS1ETtH0WAihSaNqFJjdOoTWKP17E9Htvj8ezr2+89G3/c5b0388YJ"
    "tlH4oz/76d177rlnvt/ffs6Dn8nP5I5ENN68/PKLh4THX1trHzPGdN/OgtZajDEYa7HGYIzF"
    "WhOPR9fGWIw12Ft9G5OuZa3FcZxVrP1hRaq/fPavnj2/jsA/v/TCb2Wzbf90+NBH8/1bB4Xv"
    "+7evljsUay1gsdZiLYClVgu4dv2q/f7rr1Qq5fIX/vZvnv8OxARe/PaLu3whRj716Ge6lNYs"
    "LMwjpfzQCLQSz/PYvHkzAN948YVCWK0ceu65r044AL7g2fsPPNgplWJ6eur/HXgApRTz8/No"
    "bfj040924maeA/AArLWfHRgYFFPTUwDMzMzwvVf/k0qptuGCQgiEEDiO0/R9J2Otngkh8LMe"
    "hw7eT09vD4XCKrt27hZSyc+mBIwxXb7vo5QC4AevvcrNucvcuDZTjxK7noTFrhm3666sNQ0D"
    "doOlbH2sxXo79wziOA4PPfQwYRiS8TMEQa0bwEkU2vhacbXC9atT2CSQTBJQZs3HUv9n0vnG"
    "1ufXTbbuz6yn3UJJAFfHpkBAENSQUmK0Qetoba/1K2CNBQFPP/MlcMAaAzbSVJIlUs3FRKL/"
    "tmmebdJ847OEXH2NKPPEY/G8f3jmW1hACNDaYIxBa43R+tYEjDUIBEvzBfIDmwlDRVisYJWu"
    "A2kAbBpIpMBSK4gUUB2cjUEnRBtSZ0oITDzuOA5KSRACrTXavA+ByAKWbN5hy9Z+9u8+wsTM"
    "GNdvjFJdLYDUINbk7LrnN5Bzmoil89daL7lOrRvPMpGlhHCQUiKEQBv9/i5krEFYwcJcgc6B"
    "gK25QQaGt/GRex5gdOIsF8dGWJyZwdRUGg+N2rRYRAMRaxs0nozHc4UAxHqrWizaaIwxCAFK"
    "aRAWrTS60YWSm0Qcx8FojRAO2byDthVmy9P05PvY5G/m2L2PcHDXg1yZHeXytRGmb17D1hSY"
    "eiCnlrQmBRxpsnWsJFashRVqtTJBWEXKgGq1nFpAqag+Ka2aY6AlAWsRGJbmiyyvnuPS+Yv0"
    "D25j29AudgzuYVvPdvYPHWbvwH6uLVzh7VNvcO3cKDbU4NRdIgFrYldANLYIIGVIuVKkVClQ"
    "q1XrwS0ST7AxJoGMCWil0abBhZKbJgLGIISDn3OiRYOAuWtXmJsY51TuR3T0bOKewd3s33uE"
    "od57GN55L7PXL2PCZn+2Ir6OAxkL2igq1Qh0EFYByOQEmVx2vS/HyznCieqUtSitml3ItLKA"
    "sTjCsDhXQLgW4bu42Qx9AwNs27aT7QO72TkwTMb3qaoqUzOTLM0X0YGqg099P9K8UorV4hKF"
    "4mqLGtHyBmMiBsJxUFJhidYxTRZoQcAag3Ec/Jxgy96dPLD/GLsG9tLT3kvOyaHRzBan+cnI"
    "cc6de4fiwiKuY3DbROQeQkSZDJBaUiwtU6mWsMLS3l3vdJvhril0aZaLniglsdaitUqnxAQi"
    "Nkn/nbqQheWFIjsPdHNs7y+Rc3KUVIlL8xd5e+RNzpz6KdXFEirWemRxQ5LijTUUSiuUyoWm"
    "wP4gImIy6WtCIFWU8ZKWp07AaIyNTKO1aogB8HyBcC0FWWBk6j3eOXuCS+fPoIsVjDI4Avw2"
    "Qb1YOWAtlWqZYmUViyXf7rdUcBPgDZ6lxK2NLGDsegJGa2xMQCmVxoAQhuWFIjdu3uDr336e"
    "8XOjyGItco2G/F4vYpYgCCiVC3HG2BjxRoA3ImABJRXGGuQ6C2gTM5NI1WgBgesLbo6No0oh"
    "xmgcF3BF08JYkFJRrVUIZYDnC7xso5/fSvUtL9OBhpYpzf+qYb+SBrG1BillgwUiAiuLReyC"
    "bdJ2Y24Pw4BaUE17k3VAWqF6/0epNFZ4KSXGmLSg1Qk0xMBaAsKNulBBFJRaKbSJ5mkTud7u"
    "j+9ja+9AnC7Xg0jxCVicm2Ni5DJrY9rioGnH4uKgcEU5bUUSidKnRspWLhT7lpIy7vwijU5N"
    "zTWdELRS1N5dB/iT3/lzck5uY/SAsoqXv/cNzr91DiOj9U3bMCq/n4yfJ5/P4bkeSgYUSlWs"
    "KuBk/wNdK0YxECcZKcNmAkZrrLFopZAqIpDUBiEMrpvAdtfqFICllQX+691XEen+qLVYDDNz"
    "U/i+hxECmd1Hx8DDPPKLR1kohayUahhjyLgC3xNUS0WE28Xkj7+ZZiGldIs0qiMXkkqmFkh8"
    "r1yss90o4E688iYnXnmzJehWfh4WwsgtO4Z56OeP8swfPca/vnWJl14/C9YglaVSs7Rlcty3"
    "/yCrkw9GdcWYSA0NfpX2QkmQJDGQzHE9Zz2QNah0WTY8Wl9N14rrOnGNyRBIw99/9yRXphbJ"
    "+xlItqbGIICOfA6vrbPpfdOQMJqykFIKmVggbgNqZXlbBWjdvOTCyUGmEysEvnRZmb3BT2Yn"
    "0qatvaODjq5NLBcrUfsg5bpWJ8GWEkhiQMl6DKT9u7OmW9kI8DrFt5jYsZf2/gfZ0r8V1/GY"
    "nVtifGysaUpfXx8He3vJeC7zK2UIq+R86Lb/jckvInUGq7c3E9A6OstUWqKkaoqBsKZoKbfy"
    "lBbYhddO79BRnvyVz1MLo95pv7UEUlMNIy0rpTHacOnmErPLRTCWvrxDV7vlvv4xdjz8C9Sq"
    "JcbPP08+c6CBQJzPpZQNFmg4SViDSkQPmgBvcDyUWiyz+SMc+dhRpIZAaiYXSsytlAhk3Aha"
    "U/+Ou0FXCIwxeG7Ijn3H2NI/BEBXz24em3mJl2gRA0kQJyC0at7s3K7ku3axY8cQl2dKjE4u"
    "RXUm7hMcR+AJN249BWARVtCZ81mavMKxwSt0bnoSbAGsoqt3L9t7o61mcy8kJVJKfK9ekBan"
    "i3eFQM/9WaZWQ85OLKXAXUfQ25nDMQFBqYRSAVZJrFZYHTA3uYxeHeOXf3cLbR0DEEYJReDQ"
    "3TvMq/84sz0N4qgOKJSSCOvSP9jP7PRsU8TfiUipmJivK8NxBIObckyce4dgZZzBzDi+0HgO"
    "uJ4g68En7lngk5/fycefeBr0DDhxOjU1stksnmawIQbqadQYy5ee+lM8NwPwvgex4gPk0m+e"
    "uIHbEBzd+SyV2at8cvsF/uAPHYaGfx/Py0anFtEfJdcxhOd5oJfB5sFWoHYB9CLGhGiBSVzI"
    "aq1FVKojErVa9a5oPpEOTxBUCniuj1KGfNZjcm6SX/vcOAcf+jqoZaLgDUFOQXgDSu+BqYKp"
    "gSmBWowWy91PaWUOIxmPjteNKRSLhe62tjZqtY2P1O9EdnQZLk1fpXf3YQrlGsIafBEysOMB"
    "wInSVeF1KP04AgxskI9Rpp3llUXzub9g2QM8KdUPTp85/RsH9h8SJ946/n9CoDcvaFtdZGX8"
    "JG0dm1gtakoB4HZGmp1+DkwI/lBr4Im4m7hy6T3OTgyehKW8AHLHjh35ud337nnzqT/+Ykel"
    "XObkqfcol0v/6434B5HVmqUU94e9bYt8+VcdhrcuQTAOmUGWqr1cOPf2uvccx8fL9hAEJS5e"
    "W1Zf+5eOT5w6NXpBAHmg89HHH/nNwYHBv3vi8Sfa9u29T+Tz7aS/KBqDNSZu+qIjbtPwC2Ry"
    "b62J9xYWY3T6rrEGo9e8ay1O7TxHt7/Fnntykc9nBpHZByiXloH6ycb4lTNcnMxxdWmXGbu+"
    "El6dWHn6+Bsn/g0oeoAC5BuvHf/u4cMHr5XK5a9kff9jFttx19VPtDUMagFBENDfucBHv5AH"
    "mwWjIZgkE0yyCcBpg4GnoPAjJjJ9/PT0RHj6hntyZnL6q6Ojl98BQkB68UUFECMjZ0dGRs5+"
    "EcgCGSJn3PAE+zbEB7YAfUDfwWH2FH593+/hDWepTYBt6LuygzDwZyCyVEpfWz1zevRbb7w7"
    "+i6wTLSzqgCVBFwNkDGZagzeiwlk7iKBLiKX7QDCs+MsnTwzNrd585ah4eFHXZciqAJgwetG"
    "Xv4Kly4cl6fPnJn/4btcjzEGMc4CREevayXZO3pEv6HdTQsA9BNZYSuwxXHY8uXfFp967Ih7"
    "pKu7r60t34nVhmptxa6uLJe+/7Y9/sK/29eMYQaYBqbij0zAfhjiAD1ErtQNdAL5zV2079tO"
    "T6jQlyeYL1UpAyVgFVgCFogskMqHRaCVuPEnwaSJEswt5X8AC8Kh57iv//AAAAAASUVORK5C"
    "YII=")

console32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAAN1wAADdcBQiibeAAAAAd0SU1FB9kBGxURJ6+j6YkAAAc7"
    "SURBVFjD5ZddjF1VFcd/+9xzpnOnvXPHmbaZfgCdTktrKdCKhVANYBMhyoPEJx800QeikRhC"
    "VB4MaBQTE/XBhAc1JL6ABKsBTXxQUxGBitAPCm2lrS1aWpjWTufj3nvuOXufvdb24Zy5M0yB"
    "FOKbO7l377P3Pnf913+t9d/7wv97MwAhBLP7N499u9kc+vyypYODIQTzXi8FAkFD2QclaECC"
    "QgDV+TklQAioCqoBUQ0zM9OtyQvnH73/Gw88BIQY4NdPPv6z7dfv+FKc9CXOuf+xj6H8DuU4"
    "SZKVnU7nAf/DsPpb9z/4FfPYY4+s3bDpmkPNxtBIp9Ph7Nk3yfP8UqqM6fVzn4XP7zZe+Jwk"
    "CSMjw9TrdU6cPHHh6b1/2RaL4YblwyuGWq0WL+1/gRf2P0PaSSvE8x5cnqelMQ3ae89gCNVa"
    "s9ngjl13sWnjFlaNjg5j5aOxCWapMaYWQuCtiTc5+upxDIYPXzteRjvMxx1CD0/oAQuEMEdz"
    "1WOqrfN7jh89TQjKzTtuxdocY0zNObcsXuyEivKpz9zK1p3Xkc+0CV56QEJQNJQGQ2W4HGsv"
    "xkG1NBuqZKz2ja4e4ek/7APAWkutVkNEeBuAEAKigpeC9WNbGB5YwfHTr/DmmZOoLUoPFwKg"
    "BLVwDgLa26c9zwotCKo9AHGcUEixGEDJgLWONEu57sobWbdiI29tOMPhU/t4/eQRijSv2Jjz"
    "kPKHTQWgMq5VibrCktuMC5Pn6GYdCAbrLIGAFELsCteLXRQZRJWsm/P3Z/Zw5NX9rL1ijCtW"
    "jXPj1tvYvnknf9r7FP8+enSe8jBPewgBDUKadeimLdKsjaqCgZnpFC9CqBgAcOKIRaQHwJgI"
    "EcFaR7edkrnSW0GRSLhqdJwQG7Is78V/jvKicMy2pki7ldGezJWdL0pxIoCzlqiyFTtXLKj1"
    "CFWh8JYtN+/g1utvZ6SxgtS2efG15/nznt9yceIc6qUHoPCWVnuabpbO/050qd4qAdXQy4Go"
    "VgMgVhFUFe89EBAvWGtpNobRoDz53OMc3LeX9OIMQeblV1Rpd2bJ8k6PwUUKj1kg6FIxoKpY"
    "Z4n7+koArhBUBOcsYPAiZGnOiy8/z+92/5K81a30PVTUBrKsS5p1UJVFavl2AAtbYavzQBTx"
    "niV9S0oAIg4vpddzOpDnln88e6jMai1rWVTIbYbN87LMFpoxvAuQ+UVfKKqgqjhrKerFHABF"
    "xGOdLUMgQpbnJGmZD1483ntUhauuHeeW227HqLnEstSE3Y/8ArEFIYCPhtB4FUpCFGZRTvVY"
    "tM5SFBWAwjlElPIUNFjrmJmZRYy9hMakf4At49eThPiStW6UITUoXCCsvJOxDdsoav1EJsIX"
    "OdMTbzA59UQJwFrmTt1YVBDxOGt7AuOdx2aexQwffvZl7tt79zuFGDBoIUhtlK2btvPjez7L"
    "vT/fg4jHxP2su/oapv+zE60SUar8iZ0TRLQSh7JUvAR8IZcGt9B3udKUx22oNQjJctLWLF9/"
    "+CliA8PNJlkR6IsjImPmD7dKK2KRosoBV8lqQLzivb5nVptFU431n2bdhu0UviDtdMm7ORAY"
    "XFpHNWZiqkMNz3UjT+GHIv7V2lHlgAiiinMWEwyq4L1SuMsrMWOgtmw12266g8bwKOdnUvJW"
    "Sje3+MLzytkOBKXRH5MkgY/fcieDQ0McemkPh44U/bEUDvWCq/SZEMjajiDhsi9dy9dsZOXo"
    "av52/Dzd3BEZZSCJqMd91eGkGNdmVf9pBpZtA5lh7Oqb2Lb2V1tj5wSvHmsdxhjiJMHlBS4v"
    "LhtAUxJePTND13r64ogl+RQzrx/E+DY1PPXEc+XgFA/c8wnipA4hpj7gWLsi3RCLCCrlsalB"
    "uO/e+4iiCGMMURT1xnPP79QOnMmZrcqqkcBYOMiD393MssEmBjAE+peOEOkM+GmwpwhZRlF4"
    "GxfeTczOzjqgz/sCT/G+773NWmA2vUB/MkKUneOOj7QZXfcxyI5D+xnIT0HbLUihiOn2mnB2"
    "euCvtTjq69Qb9S9cs3nL4Lnz5z7QxbueGFqtFsGmtKYm+eTWnPGVKVx8HKcNct+PmiEkahJq"
    "KyjCMPsOHnUPPtz9cnzgwAE3Mjr0g4ElS7538007R6JahKqWghEUFe2dfkHLO6GqlOXam1PG"
    "VKv3Blge74epUxACF1uOibfOAJBn00xMBt6YGuk8d3jp90+fPiwG6ANGNm/dfO3Gjeu/msTJ"
    "hkAVuvfZup1u0m63k4e+mK7ZdWMjxl8oF2pNWPNN/vnyo/Kdnx4/+txLnR+dPTvxPDAVAw6Y"
    "PHbk2IFjR459rQJUA6L3aX8EWA+MHbxh6ee2bL5l0+iHhiKkA7UG3anD4dhrhyd//8fTT7RT"
    "ZoECaL2TlxGQfMD/YWuBceCKu++Kbt+1Y9mOxuBgvZt1smOn2id/8oTsnprlBHACOMcHofky"
    "WwTUgf6KTQEyoLt4438B/FPz7yk36lMAAAAASUVORK5CYII=")

console16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9gMDg4IFM8L3a8AAALA"
    "SURBVDjLfZNNaFRXFMd/d/JmEoOxC2nUYgwxpmPTjV+tFAxUkeKihdKdool1UZNCEanYRlcF"
    "F7abLtrSFHShWNG466K1FEprKBVExTqazMR8TCITmjgzL2PjvPfux+niRZNg6YE/hwvn/O79"
    "H85V578/s0Jr02uMORyGYYPWmgUZtFl8jmWNnQ3C8Nsoij73lFKnVjWu6W5t2ZBM1dYBAsJ/"
    "hnOW2UqFwlRh5bWB34/nJ8aTHnBofcuG5IGuTjJ/Zfi/EInJG9vT9HT3pPIT492eiNQplWA4"
    "l+PyT1/jxCIiOLE45xCJZZ0gYnHO0vlOL4mEQkRe8BaeJ9y9kwUszsk8KG5+CnIiWGcAMDbO"
    "iwCOlY0NcbFzOAzOWdw8INRV/NkZ/LkiANbapQAR4e7tIY70nOTcxT5migUEwVpD0f+bIJiL"
    "C5WKL3wO4IRlDSl+++NHPug6QrE8w5mLX1AuTrN1SwebXuskCi0EI9z+9UPMPCDxzII4splR"
    "rv95g7Lvk/JquXXzHpOjj2hd38FApkDflZ+ZnK4hnU4/bwEBPMtHhz/mQv93XL85QMeOt9iy"
    "bQ/Na18mVV+h/HA51glffXkC6xS54dwiADCSnWTvwfdABBTsefdTTl+6hnpylXp5QkIsTavS"
    "bGr+BVtNsH37G4tmAFhn4xmp2FnJ97FzRQ7u3si+XeAlAggHofSAmjDFiobNSy1UStUlm+fn"
    "7/D21hbe3PwiXtgHyXawHpJ8nZJeQzY3hKeUikCWNa1rYmxs7Nm6Apw8dpS2tjZ2tn/CuhYD"
    "1RJCK73fTNC4uobBofv/eKAujOdH3+/vv+w9flzB9318v0wQBGijMcaAqsfaZmqCOUqhx+qX"
    "Gsncy0TGmLOeiDtRmHrIeH50v9Y6FUXRwlfWGm00P1ydZeSVV1VtbZ3KDWdlcPB+UA2C8yLy"
    "2b+pXbCXHQP2jQAAAABJRU5ErkJggg==")
#-------------------------------------------------------------------------------
console_settings = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9sLAxUpMzAzR9UAAALi"
    "SURBVDjLfZPba1x1EMc/5+zZbbaY5CF2e0uC6a5GxZp4K7FYqKIP0lbEt4JtVYpNBAlSb9VX"
    "UdRXwQtF8NKC/gH6Ilpbi/FBw0kWNWk3brJl43Z307MX9+w55/f7jQ9bm62IA1+GgZkP3xkY"
    "69NTJ/uiSJ1QSh0LgqA3iiLWpYhUd92RVrrWDoL3wzB827Es643Nqa2T6ZFMPLGhBxAQ/jOM"
    "0dTqdYqrxYGz575/eXklH3eAZ3aMZOKHjhwmO5fl/0KkQ7719lGmJqcSyyv5SUdEeizL5sLi"
    "Il98/R5GNCKCEY0xBpGOtBFENMZoDh84gW1biEi/s25PmHcXAI0xchXUGf4HZETQRgGgdCd3"
    "AQwDqd5OszEYFMZozFVAEPl4tTLeX1UAtNbXA0SE+dnfmZ56nU9Of0C5WkQQlFKs1UpEYYht"
    "x8Dq9Gv1LwdihGRvgjPnv+LZI9NUr5Q5eepdjLFIJpPcvP0+7h27n9xSju82/oY2BsdxulYQ"
    "w0J2ibU/W+waf5B4LEFxxePg40dpBz7lSoW9D+2l0WzwyqsvMnrLKKXLpXUAAjia548d5/Mv"
    "P2Tm53PcsLGfduBzx86dVCtl5rNzbNu+jbvuHqdSrtJsNrsAQG6hwMGnngAR4okEh45OE4aK"
    "aqVMPr/C2fPf0tfbzyMPP0oYBPRsSGJ3G9BGd45k28Ricfr7+jjw2H6smM2ZH77hl+xP/Lo4"
    "h9GKid0T7N+37/oV6mv+tTLsEXJLOeqNOoNDg9wztov8H8vclhknCAPcWRfXdbEtywpBGBoe"
    "4vKlGqWCR6ngkb+wyltvvkOlUmV4cJh0JsPxF15iz54HuHNsjJbf4mIu17Y+O/3xRzcOpJ5O"
    "bdriNBp1PM/D867g+z6Rihi5aQcxx6ZerzOxewJ31qXlt9iyeSszMz/OOSLmteLqJfLLS09G"
    "UZQIw/DaKyul8Nstq9loEoaRldqUslzXpVAoBOl0+qJl8dzf69G2SkX/b3sAAAAASUVORK5C"
    "YII=")

engine_settings = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A8wAAhKWxegAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9kEDhQOO9gd+bIAAAAd"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIFRoZSBHSU1Q72QlbgAAAldJREFUOMvNkklIVAEY"
    "x39vfC4jbo8xFyTnIA5KKeaWIxooaKXYpQLFLoFEUtkGNjinDop6iuooRAso0dBB0UzUGC0Z"
    "C3GBNEfUZ6PkMo2azYg6vQ6iOA6Bx/63j+/j//FfBA6gvrE2GngNFBqqjS6OANWhebziakUO"
    "4CgydioFNT1KQU2PciQC/WVDafeqPrTpWRPXr1X6nw4e4cHF+P3dv8jE+sZaLfCme1Wffv/C"
    "cYbNAwQGBuGn2kZedqGNUCNT2JyXFE6mTgJ6lK66fGGfAJitunlHiWtvY9g8wO1b91he/IEu"
    "Lp6oGDWgQZ+wezw46fCSIAK6x08fjd6orPJ3u3cEp/M3fgH+BAcF0dfxgk/ryc70xNjAGI2a"
    "3rEVNqzvyw4SCAAlxg5FFziDxncNlSCA4qbobDGjY2PItrmdIedJZ1F2YsjAhB15aTecPRki"
    "wKbiz/lzJcjLu8vOoUVSFuaxLcyRnpIqqkaGQtxbsegTNJTmqmkwWT0kANBgsqKNUKNP0LBi"
    "/7ll/vxVlXYiXpQkiayMLCxf2pkTM2hZET088AGY7nv+MDIq+psrQHupOD0St+DrM2yXtr+v"
    "iaJDtihpKacEKUxiwzbI/Mxk5bsnFSUeHgAU1PQoeUnhREoBHh/+7GxhH2/lSmk5c/IsHz72"
    "oxKUXEO1sd+riZk6iUXHJi1mGwMTdgAsU78wr6bysvkVIaFhnMnOATB5NbGrLl9oMFn3o5KX"
    "XGiPqZGXXDgme8ss68m0dbQyNT0FEOEl4TAO1nYvsvrG2nLgLlBrqDa+5b/AXz4B6rPFYEf6"
    "AAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
engine_profile = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAALEwAACxMBAJqcGAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAMtSURBVDiNZZPLT1x1FMc/996ZAYZ5MLwKAsIwPMZWwzMpTdRWbRRbFnZBDYZ/QLvQDQlG"
    "TbpoY42xkcTEjdGFBmLYNCbTGFOrDRoay1CIMLwd2jJTqJ3nnced6dz7c2EhHf2sz/dzzsnJ"
    "kYQQ7DM9PS1/emXXq2ZyI4YQvYoi9xlCIAzhlyVp3m4tmRp7o251eHjY2M9I+4Jrv8zbL3x3"
    "8z0d5YPWtuYSp8uBzWZFCEipKWKxBJsbd3KlChc/HB34/ORLveqB4MbCsu3Cl7/7autrX/S0"
    "t2AvM9NWbyO4lwaguaaczV0VNZ1ndWWTeCR246N3nh863n0kpZw9e1754vvrF6vrakY6O930"
    "eSo5c7SR9no7G+EUJWaFM0cb6HK7SGZ1rI4KslmtZXH5fkln3bM/S2Of+U7sxTM/Pdf9jLmr"
    "pYKBjiqepKAb/PjHHa78tkU2X2D0VDfbu0kW5gP5xhrHa6aHicyox/O0udpRSp+nCt2QADCE"
    "YHYpzFdXl9j5WwVgaKCV44driaqPaHU3WsKhvVGTw2btrap04j5kRyChPz7K+W9muRkIF03T"
    "563DZFJoqiknm3WSSiR75aW/9pryQiYUzTETiGIImc1Q8n/hWpeVfm8DM4Eo8YyOUCzcXgs1"
    "mkIP4vpONE06/wiX1YLdegiLWeK/jLzixVlu4n4iw4OERlTVuLcbLcialruVzWj0uCs4d6qN"
    "UotMT3s1L3Q1HISPHXmKN1/upKxE5u1BD801VuLxJEIIvwnwR6PxoYWgg8GeehT53+6Xz51g"
    "YyeGSZFx1zsPZGmtwFpYJRaJA8zJwORqYCv3MKnh8xfv3d7oKgoLYHLmLqm0xsb6tgZMKbH1"
    "a5FPvr6eEojBjFRGWivgqbOhyBKXf1hjdi3Csc5qsnmdb3/dZmUnydytP4lFE2NB37jP9Fg+"
    "sb4afNXQjdd1vYPF7TiHmxyktAIAUzN3Wb6XIJHSWLwdILSzexWYKHom9+lLEvCu3V7+cYe3"
    "tdRV6cRuL0cIUJMqkUic1ZUtTcvm3gcmgr5xUSTYx336UgfwlhBGv0mR+g2BEIbwI8lzwGTQ"
    "N77+ZP0/ZHB2hbH6UYcAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
engine_new = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A8wAAhKWxegAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9kEDhQMArUuEzgAAAAd"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIFRoZSBHSU1Q72QlbgAAAkJJREFUOMvNk8tPE1EU"
    "h79pSx/TFhkq1KrQBCzWQBMfSOwGA0aicaMBlC6NC3dGownq0gWRuPQvcKFgCGvNIJh0g6io"
    "iA9g8IFBkjaUKrSddtoyLkyb+mji0rM69+acX373nO8K/GPoG+YWsBxAMLrQ8zHITAtO7Y1Q"
    "ruHo9Qm9kMvXjgUQHCEQjyDYG9GTHyA1jp64ayoUBXuv9jl8XUMACUUOAfR3+xgcVZh4fuji"
    "rgbTOcm5G6ejaZ38Wz/5h0B2wVgQ2HPyxmx/tw+zycBKztPjrbXhFCvYULNYrGv7DzbOI4pd"
    "GCwXLOgfNTafWUGbMZXafroQxy1Z6WvfWbwL+l34autJ56oxae/Ibd7GanytoeeW0fOxogP3"
    "Ns/8Ss7T0+Kt5FMkifxiJfk1ljFPK6tJT7XDvEVMs5Gcocoir1UYlEVIjYN6RygdmLfWRtDv"
    "4n74czL3/YusRhdHzJXudtHTfObWWbs09f4RWjaOmnVy6VQgiKk3Yyg46O/2EfS7AKhy2Oxq"
    "dHFkcuTmkLYeCTtFmzSl1IAphK/+Mg9edSBUnH4iCMLL4gwGR5Wig1RGy9QFDl8BELcHzn9L"
    "qEnAPjkXYzis/rJuA8DYQKeQUOTQUlTFW2Njb0O1JZU3N9ftO3HPaK9pPd66ww6wFFVJKHJo"
    "bKCzyI9QCk5HYCtuyVqWxkg8zePZVUoFDKUFbU0SkXia4fAyk3MxAH7aXiYST9PWJP0hKvwN"
    "34Qihxy+rqECiYVz4bllBcr9hd+b/q/4AeSu45XOvbvTAAAAAElFTkSuQmCC")

console_new = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9sLBBQlMe6dO3sAAAJb"
    "SURBVDjLhZPLS5RRFMB/d/qchzS91AlJU8s2rVoVgYta9A+0C0p7QOYiXESLahW4ahe0KKhF"
    "0QPdBC2KWvVAiEIrM9DK0cFIJ2d08jnfdx+nxejMaFgHDvcc7j2/8+Aede/B7U1am0vGmHbf"
    "9+Naa0pq0Kboe41149TVThNShoVFm3ryvO6Ap5Tq2p6oPbe7qbkiHIkCAsJfEvEGiMceEw2n"
    "cS7E96Q0ZLKTvR5weldTc8WJtlYGBwZZT860hrh0MQFbO/C8OE0Nj0jULO3wRCSqVIhvX7/S"
    "/ewGTiwighOLcw6Rgm5zb3DeAtHKRpTaQqAr8f0g6q1kcE74/GkYsDgny6BCsHOOHQmhqibD"
    "5sou5uc0galmIh2hDOCoSsQLWZ3DYXDO4pYB034t74Z+MzKRpv9VioMth/n4JV0CiAifPwzR"
    "2XGFuw9vMpX9iSBYa8jm0uTzC4WHKsSL7jzXG/YA5QAnxOJhXvY+5WxbJ9mZKW4/vMZM9hds"
    "MMQ2RpYBhcNYC1DWgjiGB5NMTy6yf99hwl6E/r4viHPFIFTJtGsBCOBZzrdf4H7PLd72vcGr"
    "UMCGQqxSqyqw1qwBACPD4xw7eRREQMH710PFuyDwaTmyr+hb61YDBLDOolRhUAD7D+0tK12h"
    "QqF/VCAwO7207k8s73/VDJRSAUisfmc9o6OjiAj/k6rqbeT9PEqpeQ/U/bFU8lRPT7c3NzdL"
    "Lpcjl5shn8+jjcYYg1nZTmMwRhPogEwmGwB3PBF3+efED8ZSyeNa63AQBKVV1roIWVnxIAjQ"
    "gfa1MfdE5OofD/xwDK05bmcAAAAASUVORK5CYII=")

#----------------------------------------------------------------------
engine_stop = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1QoRFy0Na8CcwAAAAsFJREFUOMttk7tPU2EY"
    "h59z6QVtjcbI4CWGxkAreGlquAmpNoiamJC4sRBY/A9cOjgYaRwcTByMC3HQwbsxuJhQJJqw"
    "iMHEDg4otdQWSmmhB+G05zufA6WC8iZfvuRNnt97+eVV2BKPwmE9PTHxRMBVdggNxgRcjkJl"
    "M6f8Az9r9PkuXbx2za1oGgBSShACaVl8ePjQ/DIz817AlShYNYEq/MLv8/VGhobc8+PjmPn8"
    "tupOr5f6jg4+PH1qJpLJMQF9UbC0kVDIkZ2cfBk4dqw3Mji4Aa+ugmVtExCqylo6TSAS0Vfn"
    "5o4slUpnBsPh51pnJvPmeGNjz/mBAXc2Hseqr0ePxSCZRGazG7OfOMHeu3epJBIYX79yPBzW"
    "jVTq6I9EIqj1qOrj/uvX9cy7d5QLBdS+PtSWFpSODvj+HXX/fvYMD+Patw9FSkrj4/wuFGgO"
    "h/Wpz58DuqIoICXlQmGj1ZERcLlw9fbivnEDXVFwejyY8Tj5O3ewgXXDQAqBAqj/eSUl4v59"
    "5NQUzl27cHq9WNPT5GIxhG1jAzYgqztSd/S7uRl3KISu6zgcDnYHg9SFQsgqLMplxNzcXwEp"
    "RA1WW1rw3rqF0+tlPR5ndXQUp8eD7949PO3tmLkcxrdvyJUVAHQp5YaaYSAsi7q2NlxVeHF4"
    "GNs00YAD/f3UnTrF+oMHoGnY1aLaBSm7K8Xi4UBbm1ZKJCi9fk3l508Wbt6knMlQXlwk9+oV"
    "a7OzJG/fRtE0fH4/6aUl+8fycl6JgVODtycbGrpbg0FXKh5nrVisLWvrUxwOGpqaSBcK4mM6"
    "vWBDpzYGIgJPcsVil2kYhwKtrXppfp6KaW6DVYeDBr+f2XxeTP76lbKhPQqp2jFtduI/eLD7"
    "7OnTLkUIbMtCWlbtTyST1qdsdsaGrigsbrvGrSICenayV4VpG85FYXkz9wfHTVL214b3FAAA"
    "AABJRU5ErkJggg==")

#----------------------------------------------------------------------
dbg_enable = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAABl0"
    "RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAIkSURBVDiNjZJNSxtRFIbfc+cj"
    "mZkkfjSCEFuQtghCwUWj0KXb/IQs3GlBKBQ3waWLoNBfIBSkJYI/ILsupIsuGrIqLQGRoEak"
    "6KLNmExzZ+aeLuJMZ4oLz+7e97nPORwuMTMeUvOVvTrAW0TUZua1brN2AgAUCVZeH9aZeUsT"
    "oh2Eaq21Xz3593h3U9P1vcKjojPyPDV0+z0wL3abtYEAgOWNxmYmY7x5ufTMnCsVV4QQn8rr"
    "DSduT7STny46mm7AzheEputTAFYBQIxz2llceOxYVgZP5maEbZkxMF/ZnQVg64YR+8xM1gbw"
    "CgBEeb0xC8B27GwMTE7mbKIxAKCsG8YouQ/dNDUiEU9QzjnZFFDIWZqmaauRwDAzuf8EYFYv"
    "YsFEwUkB+ZyFMBwDADwAKpmzYoDIiwQeM6eAMFQggnd37ARSDpN54EsQqB0JOreDPynAHXgQ"
    "QrRjQeBrKYGUklkdA4AOoDMcjlKA63oyCMLju+MpK2XfXF4kERPA10hwKv3A/vzl+71At1mT"
    "AFINkkUP+crzld0egFLiyu82a2Y0AZY3DnvMnAJa+1Uz7kJ0npuaLmUsG74coX9zfRVlOgBo"
    "gs6fPy2VZooT6LtDfPtxdpWQgZkPPLe/JDTdGvb7koGjKBMAEITq4OLyxnNvPZxdXEtmPkK6"
    "PgS+/+739c9bX47eg7me2kF5vZElom0Ab4noo1Jqu7Vf/XXPLkS3WUv9mb/vR+THZPMfuQAA"
    "AABJRU5ErkJggg==")
#----------------------------------------------------------------------
engine16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1gEFDSACcV9azQAAAB10RVh0Q29tbWVudABD"
    "cmVhdGVkIHdpdGggVGhlIEdJTVDvZCVuAAABsElEQVQ4y8WTwUobURSGv1ixTpKWjtEEbSWl"
    "MBKQgIIIA8Wi0EDpMpY6T9AXKKT0AaR5kY4h5AE6goHZBFy4ySY4ghmxi5kmjC0z3igtdtHO"
    "dGJNNy56Vufec/k55z/fhVtGYlTh+fu9qzDf3d4Y+W48TNRX77bSSkkH8C1DA6iUFaoNa6h2"
    "XSwSSCslvVJW2D/0aFLS81kJ+4sgn5WwKenrxWlWF2Rg7youMh5X2z/0yMmTbK09iu7UQga1"
    "8Kd+PcbCxLcMrdnuAXDsBNTMbvDpwKFmdoPPfQFAs92LxhsyMTQsn5VQCxlqZjf4/vXEEO5R"
    "feJ+bi05u/h68+ljudXpY7tiyNiog0pZQS1kAHiQllLCPaq36h/0y2+OeS8pyeE4lbJy8xaq"
    "DSvq4Pzi8mK++OwtQHKu+ObMFwGQanX67Jjibw92tzcSvmVotivIz0gsPZm6e/5jYnF++eXH"
    "O6mZlRcrD1MAtivwLUOLbyERB2e9OE1OnhxJneMNaLZ7QyyMxR+sLsg43oAd85RWpw/Ar7ZP"
    "cbzBbw7+gXK4Dd8ytBCsasOKzjeReOu/8P/jJ35PtIQR7i45AAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
run = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAAAQwAAAEMBuP1yoAAAAAd0SU1FB9sLBQwQJIv4iIsAAAF+"
    "SURBVDjLrZLLK0RhGMaf75j5TliwGNFk4VpColkqqWFDfeM2l6WUk40NC8U/oCiaFR9WFCYp"
    "Z8GILMhKlHvJIDVSLkVyOWdmPhsjYZgjz+p539731/PWC7yJcVrEOM2AQUnvJoFMEAnHjFP2"
    "JwAAi73EmWw2yTOOUeplnJqNAmDPa0Fvk9+caclXJIlsMk6zDQEAYO6yBx1VI3JVqaeQEOwx"
    "ThsMAa5eAuCnLpRlVSZ01g4nyebESccoHWKcynEBACAkNMxedOFMX0dv0yLNSS9uJhLZYpzm"
    "xQWIavtOxXSwHV3VU3J5QW0BkYjPEMBEKCosbTi8WsXG0XIYQsx9mYm1nCbnotHah/mDodDK"
    "ju9RCHhURVuIC2BLdcKW4sLAUutz8PZkVwjUq4oW/Dbl54Y7cxDX9xfonqnRQxHdKwS6VUUL"
    "xzzzY/Gg32At4NPX9tUnIeBWFc3/2yORqKkbk89NkmzVwy+bIiIaYkWOmSASEeNa+PkeQP9P"
    "kf9dr/99iRDYhq6rAAAAAElFTkSuQmCC")

run_eng = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAAAQwAAAEMBuP1yoAAAAAd0SU1FB9sLBQwLICWjhwgAAAJu"
    "SURBVDjLndJbSFNxHAfw7/9sO2cXsxnTafOSNxwqoxukphlemFAdw7zsJYvIgdFDWVAk1FsJ"
    "FUhR2El7MQiim6JRGBWMCRIzqSbkPUqRbdLmpm07O+f0EmJU1vo9/R5+fPj+fvyAH8VydB7L"
    "0YmIsqiVRkbuEgoTLEez/wUA0JWb6jQKOfOgupO+xnK0IloA5VlH0Fb7TJGsy7ZSFHGwHJ0e"
    "FQAAPfOtaKm4zVRstuQSgg8sR9dEBbhDk+Cm67Fl027ZqT231IxCda+6k+5gOZr5JwAAIlIY"
    "j+bOYIa3o632OZ2hzz8Mad1IxcXG0spzLzeunpWvFW/Y1YNXgxoUxXcw7uCLnPykqtf2Uc9i"
    "YdOd/aLGYB5qN59dE5j/uBf7ko7DMe6Fy2UiZTkxGJvzaxQbsvrqS1LUV+UDO/8IxDOZSI8/"
    "CMe4F6YMLYypsdJySCDlpgRKrZSr3834ICei8rfANm0dcpX1OP+4Xwj6S4kxNZY8sU+6I8Gl"
    "N2FBMpgLjabRzwEq4HMP/3LEhuR26CQjLjw8FMnXW2SWkmwqzIuEXw4MjQ1cPyB+ne72LQlU"
    "mUkntVgKrD8lCPALsE3e523O3m+R0PZj9inPzbFZv8a8NZFSxsYVZxbUnkRMUiNFRMEx4ZU5"
    "P3ldqwHp8tOjAi+E3koSavpPDM4WNn2Zk8dl9SVoGfUOY4I2kKa7RBFRyEtbL7M5F0CFPF0r"
    "K4ii1B3mg62SKBX1WsOzACBqDOaGXSnqkSkv3s/4SbpeJXkWeZnNuYCGYoMIlb6Z/O3Xi08P"
    "2OREVAZ87uEWS4H1Rt+Eiwp5uqDSN9uuVMZ9B/oI7MUkMuqvAAAAAElFTkSuQmCC")

run_neweng = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAAAQwAAAEMBuP1yoAAAAAd0SU1FB9wGGhIjNJlzwGUAAAJ6"
    "SURBVDjLnZJdSFNxGMaf/zlnZ18O51zNlfjVrE1J8krIvkhNIpokpRYR9IEg1EV1KVo3ZZAG"
    "i7zwmCF9QnRTgohdFA2SMC2yiZqWbvm5TaZburPtnH83KaRCrOfqgZf3x/O+PMAf2QU+1y7w"
    "KYhTzKphyWPCYNQu8Pb/AgAwFuWd0Co45Yuy+/xdu8Ar4gWgyHIOt453KVKN2dUMQ/rsAp8Z"
    "FwAAXs7U4kpxq7J4V1UOIfhqF/jyuABecQzCjwrkZxxgrx5p0fBs8rMj93Y8OXS9NYNSmGhQ"
    "d14OGa7RYEK5HOTV3EZUMSzC0fUGadoc5Krb+Siz6VTvpPukx20SknU2u0Zt0EEaGQIdp8xG"
    "gKnhwygz10GeLcKHIQkWcwLMBhVx+2zVHL/fDNVDNWW3ZRPC7dwwAcdS9H0LIC9LD2uaDkui"
    "hMIcE5J0NrIcHgVFg6xkZqapHHOvA0hRNcILegxOeWFN06GzdxBhqT8W+ZXlTlSVZEzNv2KU"
    "zFvRqNf32ixP3687ISpqYFWeRcVuCyJRiuXIl0BM0bw95vM2D3gymZ8LlzEfaUm49ODiOMjR"
    "sXUJjqXW40bHLIYnAyjN3wKeK6RLHkOlItl8hlJZ6hkSWddEYE6r0voJIdJfgFDUj4+e51HO"
    "MBLlIg7WlKRSFlg360PpxgaGyFJueiLrdPnBiL627junHWt7QG93XpCcgx2fAtO17VX7MpSf"
    "vwcwMB4kmSY19S1GWafLj8o9W2WoTTWrD18xskwfRaTwIoDGnqZKqYm8zuOIrAotePvLClKq"
    "XROBOUb0tdVPLNY4G0uSVvbIv7peWvdubyC4XJyoUcx33zzoWDv/DYt494Qtmmy5AAAAAElF"
    "TkSuQmCC")

run_ext = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAAAQwAAAEMBuP1yoAAAAAd0SU1FB9wGGhIjLxMWCYkAAAJS"
    "SURBVDjLndJdSFNhHAbw5313dmZrM7FV1gwmObMM04KMbGbMi2rrjKIP6aIgLIjahX0QlaYo"
    "wcJG6UWsUzdSIwIDI4qKkCAIrKXW1Pahk7ppZWd2VDhzZx/dhIQf1Hqu/vD++cHzvi/wOxzP"
    "FnE8m4M0Q6cHBblHKIY4nuX+CwCgMxfvX6hkVB22O2wbx7PKdAGY84/Cse+ZMldnPE4pec/x"
    "bF5aAAA8Cl/C6arbqqqS6rWEoJ/j2b1pAaNTw+BHDqDUUKk4Y7mlViuy7h+8qXfXO+2GfwIA"
    "IDo1hc6udvT19cKa3cweNrgOkah6uKbOWl13+YLjz11mLoANFeFYqQterxf+0CDWW8oQGllB"
    "c5Ysd+/euYcqlUx5Q32zaV6AMhRerxeF6wqwqsCAaFTClq2boVYvoP6AH4RQdt4KRGaRHM9A"
    "IDSIeCyG5y+fwP3ihvzgodv3/dtoYmgoCEEQulucjoo5gZSsROXSE7BabIjJcXyV/GP9cqcx"
    "Ep68PjExoSgr35Q6ddJuF0XRPGcFm74RXa88CI0Mw7TNhFxViZz4nM1lLss8QimJD3z4xASC"
    "/rBWq43MAiZlAW++dMgfVe9i25mzCt1iXcaGjaW6wjWr2ygl8XyjkfGM9UCSJFdT45XWmRVS"
    "LU9rEq8HH/fm/bS1W3dxGb4BHwK+INWv1KciP0TG87YHlh2WpEajqZ31jMlk6m4sER0HcO1q"
    "Y1tCrVhUTAhlBUHoNpur7IGgPyxJkisYDNQ21DdlTV/63/56i9NRIYqiWavVRs6fu9g68/wX"
    "j1bd52bx6AUAAAAASUVORK5CYII=")
    
#----------------------------------------------------------------------
run_sel = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AIgAigCFCaWp1QAAAAlwSFlzAAAAQwAAAEMBuP1yoAAAAAd0SU1FB9wHBwwqM19+xgcAAAHl"
    "SURBVDjLpZFBSFRRFIb/+2bmPseRsnjhMMyMKZNMJVESLYpKcFqEd64RZkELrcXQJpBcuGgZ"
    "ges26VV3QSYRWCBqA4FYU5RaGUlmTOX4Ck1U6C2mee9dN400oeCrf3XgnP87h/MDv8UF3c8F"
    "9cOhlPXCRe4QBbNcUP5PAABa3YFzPo9bvd/QQ29xQT1OAaiLXEZH45AnqO1JKAoZ54JWOAIA"
    "wMD367gW61ZjBy/sIwTvuKBnHQEWs58g0k04tLvW1VbfVax6vHcbemgnF1TdEgAATPkLD/R2"
    "fM49RUfjMK0sq24hCpnggka2BMjrzepD3Ju/ivZTfeqxaH2UKKTfEcBNKE5oVzC9OIqXM0kL"
    "Ug4wxmQikZAAwBiT7j8Nk8kv8OIobGmh2LUdkZLjSL2dsjM/PprRXPOgz/aXjiEFXdfBGJMA"
    "QPLmM73q3MVAZ9B/2ISmVqKMVuF15olpWdbSkTB7tK1I+5mfjcfjrYFAAEIIUnCBhERVyUks"
    "rS4g+b7P3ukNTu3Val8Yy1lpYH7DFAoApp1FZnnGnv06bRrpoudwKd+efUjtyPdDodD58vLw"
    "7c0A8lX6sdwV4Qs1/tMjvnCpscHCdbOu6yj4Ae+mN2PyxiVjJddPQORmyYyNplrxP/o7xjU/"
    "k6h0eKQyZwAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
kill = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH1gIQDictt+6SdwAAAehJREFUOMuVk8FKG2EU"
    "hb87mc40iTODEJlK7UZDxCCGQUqaMASCSGODdBe6ECJddOcwG/EJXBt0ZcBCwEVJVgWtr1AI"
    "PoBQXAQKhRZc1EBJMX831hLItPbAvYvL4Ttnc4UIhfDIgLcAA3jdgC/jfHoUwISjeXgOcAFH"
    "QHWcT4tI91KwWlhY0J6kUloKVkPw7g0wYS8NemJ3l0yzSRp0E/buBQihOAXFbLksej6Pns+T"
    "LZdlCoohFPmXdqB7AsNep6M8z1Oe56lep6NOYLgD3b82CGHFhaWM74vh+ziOg+M4GL5PxvfF"
    "haUQViIBJuxnwUgEAaJpWJaFZVmIppEIArJgmLA/FhDC+jSk5woFjFIJEcG2bWzbRkQwSiXm"
    "CgWmIR3C+gggBDGgsXibruk6IvKngQiarpMIAhbBMKARgsDtCuHVLLReLC8bk2dnEIuhlKLf"
    "7wOQTCYREbi54WptjQ/n54NLqDfgnYQQewxXT8GaPz7mYbWKUgqlFLVaDYB2u42IICL8OD3l"
    "YmODLnz/DJOawGYczJlcjnilcmcUEVzXxXXdkVu8UmEmlyMOpsCmbMPXl5CaPThgol6/S/89"
    "wAhARLhutbjc2uI9fJNDGD4DecD/6SfwEZT+CQ4H8GYi4i+idA3DHjR/AZfefQgctOETAAAA"
    "AElFTkSuQmCC")

#----------------------------------------------------------------------
tab_edit = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAAK/INwWK6QAAABl0"
    "RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAIsSURBVHjaYvz//z8DJQAggJgY"
    "KAQAAcRCiuL7G42Df31VW8PMo8vw9c1BBsYfT+MBAoiRWC882aEUxcIetpRTxJaBX9GQ4cP9"
    "4ww3ds15CRBAYBfMnz/fGUi1ArE5Ns3iHNcZzPXiGHj5jRne3b3OwMb4i4GXT4KBR1iOHyCA"
    "YF6YrK+vqSkuLgLmMDKCSYjMl7MMnL85GPiVXBl+Pl/BwMbFyPDwwg2GHz/+/fv9/YM+QADB"
    "DBAREuJnePToJcPv338hocvExMDx+xKDsugTBn4VP4YfT2cwMLH9YWDlkWfg/PuQ4QKD/Z+I"
    "3KJbAAGEFAuMDMzMzGCNLCwsDP/enmCQ4X0E1TydgYn1N8OvTwoMLw+dZ2A3L2L4ziz4D6QL"
    "IIDgBoA0MjOzgDX/fXuKQZTjFYOYtjfDrxdzGJjZ/jP8/CTP8OrwWYZfxuUMLCKqcGsBAghu"
    "ACMjyAAmhk/3DjAIs7xm+P1fmuH55ckM/xh+MHx9J83w8thVhl8mFQzMvOJgtTAAEEDM8vLy"
    "/xUUZLllZKQZBAR4Ga4f6GVwCG5i+HBsDsODk8cY3rzhZ3h78zmDjHcTg6CsKgMvLzfYqz9/"
    "/mTZv/9AA0AAgQPxwYPHYAwCT+++Yvh1dQuDor4tw8fXbxkenL/J8MsgneHGgUtA2UsYUQwQ"
    "QBgJKcxO6LuRkjiLmaYiw3/Wn8e+v3qd6NNx6R6uBAYQQIyUZiaAAKI4MwEEEMUGAAQYAPMu"
    "sD+kP4HxAAAAAElFTkSuQmCC")

#%%-----------------------------------------------------------------------------
# Autocomp icons
#-------------------------------------------------------------------------------
autocomp_arg = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAE4gAABOIAEWfZneAAAAB3RJTUUH3QwWFDsLYrl9DwAAAI1JREFUOMvt0zEKAkEM"
    "heEPFL2PnZW1nSC2th7CW6yNtY0HsrO0V0FFUJC1ibAMgmuxIDI/pHiZmfDIJGQy/0WJM2ZJ"
    "rsA99ARHrOKsNj3sksJTtEJvMYwok3tpgDn2kXgkD9oVfUMH3bqOL+hj8MZJla8dL3HC4kPh"
    "V4/XuDbx0SNsmpieA8Z5kTI/whOIWS0/Rzz8oAAAAABJRU5ErkJggg==")
getautocomp_argData = autocomp_arg.GetData
getautocomp_argImage = autocomp_arg.GetImage
getautocomp_argBitmap = autocomp_arg.GetBitmap
getautocomp_argIcon = autocomp_arg.GetIcon

autocomp_key = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAB3RJTUUH1gELDiQmy6mycgAA"
    "AAlwSFlzAABOIAAATiABFn2Z3gAAAARnQU1BAACxjwv8YQUAAAJ1SURBVHjaY2QgAKYu3sT9"
    "69evhUAc8Pvnb2Yg/fvnr1/Tf//6VdTXVPiXEZ/m6Uu2cP/4+fOZpJgQn5GuOoMgPy/Di1dv"
    "GXbsOcJw78Gja////9djwmfAr9+/NqsqSPM5W5sw3H/8kmHnwTMMd+8/YYiL8GcQExHS+v37"
    "dy1eA/7//+eora7EcO7qbYYDR88sjQlwZFy/dc+1fQePM7g62TL8+fMnF6cBE+auFf775x8D"
    "FwcHw8u3HxjaK1JjQOILJzdoHz56ikFKQpThz+8/QjgNKEgOfvvv31+G7z9+MPBwsDMk5zdN"
    "AIm7BCQd09PRYHjy7AXIBZ+YcRnQPmVJ/o8fP21MDbXYpMVEGT5/+WohJqvRYG1uJOvv68aw"
    "aOk6hrfv3vVijYXOacuigVE1w93enEtMRITp+8+fDD+ALuHn5WF4/PQFMBYOMly7fvsBMJRU"
    "WNA1d81YHvzzx89pbnYWPJLiogz7j59jOHfu4h9giLP8+P4D5Ox/3759W8LExJi0YekU1HTQ"
    "M3Nl8M+fv5Z6OVuziwoJMOw6co7h0sWLP4EgfHp31cbYzCr+xdPbPiLrgRvQN3u1PzCVrfJ2"
    "sWbh4+Vh2n/iIsPFCxe//fr5y21qR/kxBkbG/9i8ywiJstX2P37+2hnk4cjOzMLMsOfIGYZb"
    "N29/BtrsOaWj/Ci+tAKOxt+//+63NjVgFxYWZHj27BnD7dt3fwD9HEtIM9wAYIKIPHD09P9r"
    "128wqKmqMijLy3IAvTM1Jb+RmZAB8DCo7Zzl/vfv3+2WJnqMO/Ye/gc0wG52fx1BF6DEQkl9"
    "v8PPX7/3/vzxy3lWf80BQppBAACEQyxk1zTAqAAAAABJRU5ErkJggg==")
getautocomp_keyData = autocomp_key.GetData
getautocomp_keyImage = autocomp_key.GetImage
getautocomp_keyBitmap = autocomp_key.GetBitmap
getautocomp_keyIcon = autocomp_key.GetIcon

autocomp_folder = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AALNSURBVDiNtZQxbyNFGIaf2V3bZye3SgQpkjQnTjmJMkiHEiGEoIgpEBVtSn4D5VHxA2jI"
    "f7iawg0ChGSlIaC7JkFKcpKP3CUhjh3venf2m/ko4vg2xBExEm8zGs18j955Z+YzzWaT/0MR"
    "QBzH4fLy8v3bNs3NzfXb7bafGryysvLMGPMQ0Emb8jzvrK6uPt7Z2elOBRaRdzc3N3HOoap4"
    "f2lOVTHGsL29vbS3t/fl+vr6t+Xiw8NDAI6OjrLbwCoiptPpICJ47/Hej8GLi4v1/f39r7vd"
    "7jdXhapKHMdX48+7u7uf3AA759R7b0QE59w1sKpirWVtba0+Pz/PzMwM1WoVYwxBEOC9Z2tr"
    "66NbHBcqUuCcwxZvwGV4boX+RYIxBoAgCMbw3IqJH34+e5I25McHL2yz3fYRgLUFRSEcnApP"
    "d4QgCAADhKNzv3Gi/7hfVY9WPjaIOacK7x89Omm1niyNM3bOcXzh+fC9B3z2wSO0VD8yOVGl"
    "pTC1wpPvflhoNj/VccYiQporC/Uax72Ml2fD22kTdK8S8vb9CkEYDEoZi4oISQHvzNRAIQqC"
    "qcBeIbeOwAS9MbgoLi8vLQxxo4YqROHdwUkm1Ksh1gomoDsGX0bhSC3MNioARHfgOq+kuUOc"
    "p16tkA0twGnZMc45sgLAYMXfAHhl9Csv51Y8Xq+/kF6So15flx17EWFoFeuUQeZIcsGKnwiY"
    "GEcecnyeIt7/ec1xIYJ1SndQ0Dkb4vy/w8rqVwLOelmhzh+PwYBPc0etEnI+FGRKKEBeKN1B"
    "bjHmrzKYQeZZfCtmrhExe2+6pwYQGEOS5KJezwCiVqsVbWxs6N6rnNNexk+/HkwNBXDqGSRp"
    "VZLuiyvHtTRNv//tj5MvikYtukhutNY7yKiqSt5/9cvzp18d/D7qAhVgCVigFM1/kAf6wGGz"
    "2cwiQICXwGuu9ZSppSN4AfA3HMLOCbULw4oAAAAASUVORK5CYII=")
getautocomp_folderData = autocomp_folder.GetData
getautocomp_folderImage = autocomp_folder.GetImage
getautocomp_folderBitmap = autocomp_folder.GetBitmap
getautocomp_folderIcon = autocomp_folder.GetIcon

autocomp_file = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABmJLR0QA/wD/AP+gvaeTAAAA"
    "CXBIWXMAAA3XAAAN1wFCKJt4AAAAB3RJTUUH1QYYDQkr4Wx8tgAAAZhJREFUOMu1ld1qGkEY"
    "hp9vVo+anCriDSgq/lGStb2bXkQJpD1IYjD2wvpHQQRRPBHaHiwoFAIhB2X360Hczbgb3Amm"
    "Hww7s7s888477zDwn0rizmg8vAA+HAJT1cuz9+cfd16OxkM9tEbjoca8QnrW1WqF53moKiKC"
    "yMOi7H48tpRSrVZ3OBmwDZjNZhlIujqdDqqaeb8X3Gw2KRQefwnDcGf8lPpcsIgwnU5zN6zb"
    "7WKMcQMbY1BV2u02AMVi8dkJyYC///iGfzJARJhMJrkA3/cJwzAffPL6lEqlQhAE9Hq9p9Vs"
    "fbYT42RFEASICMvlMldxq9Vy9zhutVptr2LP85Ic54LTS4w3054wvXQnK758/cybwVtEhPl8"
    "7hQ3p1T4pwNKpRKbzSaxwhiTqLYtiPtRFLl5vF6vEREWi8XLHRC76vV65nCkfXdWbG/GPo/7"
    "/f7zcmxXo9FI1MUK009VdYtbuVx+kaspAUdRdHXz6fr8ENivn7/fZe681GRHwPG2HQGvAAN4"
    "gAJ/gXvgD3AL3G3H4fY7/wAc1bAz9NMAcQAAAABJRU5ErkJggg==")
getautocomp_fileData = autocomp_file.GetData
getautocomp_fileImage = autocomp_file.GetImage
getautocomp_fileBitmap = autocomp_file.GetBitmap
getautocomp_fileIcon = autocomp_file.GetIcon

autocomp_dbg = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAABHNCSVQICAgIfAhkiAAAABl0"
    "RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAM2SURBVDiNpZVNaFxVGIafc/8m"
    "M5nJZH6j+WuHChEKWpF0lYXgwsUIrSiCzEJQGheuxIUVcecioSLowsXsZ+2m2SgUC6VFhtBK"
    "/SkWm6RmMqGZnzvNzNzcmXvucWEmDHYmU+O3PO/7PbznHM53hFKKk9bicuEb4BSwWsznbvZr"
    "4qTg8x8UvnsmMX5xdirG+u8l6fsqU8zn/urpxgmTfhUNBy6+f+FlxiyDTtfTf/5j9wvg3Z5H"
    "OwlY17UP33ntBcq2y51Nm6Vz8xi69ka/5z+DF5cLl+ITY2YqPs6fu032Gi7xiSCWqUcWlwuZ"
    "nm/gUWSyKxPAD0KIU0qptzbWLt/ok199/nRK7NQc/MPrsdseM+mIuv+w9ibw5fDEQtwNR0Ln"
    "F87MTCHE9Ux2ZalPNTuefwQF0AQ0212A6tHagLRzhibmXzx7hkQyzsJzsxpC/JjJrvR2d7tc"
    "2VcBQzuCakJQtdsC+G0oGPg0GY+qtiu5v22TTMaIhoMa8NmhvrZb2ReW+U9rciLARtlGKuUW"
    "87mfhoKFEG8nkpPCbrr4SlGxHaan00II7aNDy7nQmKUOOhIhIB62uHVnCyn9Qj9nUOJYIGDR"
    "6UoAGq0OkXAQUJHF5UIIuBKNjNF2JfGwxYPtGhW75QKXRoGl43bRNQGArgkOOl5P+zgaCSRO"
    "z8RE2/UIWTo3b28gpf9eMZ/zR4GrraZDwNIBMA2NVssBqAMvzU/HmXs2AcBmqUr7oAtw/d+Q"
    "J8BKqW8f7dVUaMwEwNA1Wo6LUmpD08RCwDSxWx2EEHieRNe1x8V8rjQSDKweuB2/YTeJhCy6"
    "0sc0TIQQc76v1jd3agRMjca+w/qv20jpZwcwngRvrF3uoNTnpVJZBS0dKX0M00ApNVUr74h6"
    "o928eu0u127dU1L6XxfzuRuDwEPHZub11UfpdCI1PhHF1KCyV6Veb7QS07NpYAl4WMzn7g1s"
    "5rixqVS9YT9ORScn6UifWDJGrd4IFfO5NvD90L7DOm66XfE8D09Kup6PUgKUEn1P+9g69gfJ"
    "ZFd+CYZCZxPpFK39fexa3Xlw9ZPQ04BHzeNXHMfZ2t7col6rS6XUhaeBjkz8f+pvn2Fd+RYA"
    "CrEAAAAASUVORK5CYII=")
getautocomp_dbgData = autocomp_dbg.GetData
getautocomp_dbgImage = autocomp_dbg.GetImage
getautocomp_dbgBitmap = autocomp_dbg.GetBitmap
getautocomp_dbgIcon = autocomp_dbg.GetIcon
