#----------------------------------------------------------------------
# This file was generated by /home/tom/Desktop/PythonToolkit/icons/ptk icons/pathmanager/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

pathmanager32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAJOgAACToB8GSSSgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAW7SURBVFiFzZfbb9xHFcc/87vtrr22t3ZtU6c2qUJRk9JyiVpBU8EDaovUJyIaKiQeEG+8"
    "gN8jVaJPERIJb4h/ABEuQiKACilCoggQCWpiaFIHR01bx/Vtbe96f5e5nOHBXmcvNkQiIow0"
    "+l1nzme+c86ZGeW9536W4L5a/38AiDofTp8+/Uwcx18BEJEDG3nvTVEU3zlz5sztewowNDT0"
    "wxMnTszkeY6I4L3fu3ZWpRRzc3NfPHXq1JHz58+7ewaQJIkrioLl5WWstTjnEBGcc10wALVa"
    "bWRqaupx4Oo9A7DWSu9o20bbMB3famEYfnN2dvbVf2fAey/nzp17964AtNbWGEOWZTjnuqqI"
    "7FWAMAyp1WqnkiR5sVqtBkoplFIAdN6LiJqdnb1w9uzZr/1HAGOMWGvRWu9NQS9Ej0JVa21V"
    "a00QBCilCIKAIAgIw5AwDEmSBO/9p+5WAdc50k4f6Lx2QgBYa7uMt2sURW348K6noG3gHxtD"
    "mGScMAjweFDgQw+7XXnuZNDeZKqUwotHGQUGzNgjH3351V//s/1vmutosZ596W/ff/lSF0BR"
    "FGKtpSgK1rNhvvzcJ9nK9E6nPeTWWubevs7GxhbeC7WREZ48dow4jlB9fxMDRwACpdjaarkf"
    "vXZ1GrjUGwW2DeAI0U5YXM/6ZCvyjL9e/hOHD8/gKyMoL6xvp/z0wi956unPUSqVDlKcKFQo"
    "a3Lr/Rr0pGLnnL7j5RHO7Z8N52+8xeNPHOP5p49ixWNE8GGJqUMPc3Ph2oHGxfudKciMVkG4"
    "Cj0+4JwrrLWICOUkwbruyXXOsbK8yEa9zvDwIBf+sE4Fz+iDY2w2UwIvNJr9irVLroVKNaKV"
    "aQOs9QFYa7OiKDDGkJRiTMd6UBQFc1f+wvTMDI8dfRTvdxOUcRgrbG7n6KLgAXuDF4Zeo5Fq"
    "3rRfJ1PTeA+ZcYj3JJFiOy3k8tR8vQ9ARDJjDLl2DIx0K7CwcJ2Pf+IJGoXw/mqDRqrJco0X"
    "B74BXhitBIyXVzjxmWcRW1B+4wdczL9Nrt1ezMRRQK6t9q+8IvspkDpnMSRUKgnG3lHAmpyW"
    "UVxeWMGLEAUwXI5RKgAfosRhGqucfEGBywiUZ3J8gmyhe60Kg4A0t3n7uRegZa1FS8hQklB0"
    "ABRGePv2Jt7DYDkmyVaoFO/zYKlOHFrKsebF5xI+/dSzEOSAw7mi3xG8Jy3MnqP0+YDWmswo"
    "HohL2I4oEO/ZTe+UXMZnJ//Mt756klJ5EBUolM+huAVmAdI6mPcQm/TZF4FcH6CAiGxrbSik"
    "RBiFOOd3wswKE5OHWN2sMzIwjDTrnHymRmVwGBqvQ/MNkJSudBWN02r1R0SmDd6r+r4AWuuW"
    "cw4TlLEChbV7aXZ84hBZmrGxtYSyliQuw+3v7nRqJ9FmR24rMUZKrG1p3tx4lN4t73ZmCJRa"
    "2hfAOde01mIoY1zQFYYAU9NHmOIIIZqi+XsovQPJQ+ATFIJCcf2dLS6uv8S2ephMTfYtFA1j"
    "cPjFg6agaYyhkAjtBOP6t+zihVb9A9LJJnggu0kFRaXyGNSep3XtF/z9vWGGxqrE5f72OtXo"
    "tLW/AmmahiLiHGGYaumTzxrN1sottpZv8bt8g2rpIQ5/KCIKAvJCuHHp5/zqj9vc3rjKSHOT"
    "semjxOWBrj42W4VtLs9nSqlRoL4HoJQaOH78uMqNd0SlcJ/BE0QJycAIcbnKz+Y/z+vX3uJj"
    "E/OMDaTcWh/kytJHMKWjjEyOMjwxQ1yqdLX33rO+ttZYuvKbRWAYyFV7U6GUGhwdHf3wk1/4"
    "xm/t0CMToRLBd6/7O73svPNeEGtwJldeHEGU+DBKCMKYvXiFnaVZ4a0qfeDE+frNKz++cfF7"
    "PwFWgUXVeTRTSo0BNWAIEOC/2nL3FAVUgQLYBpa899uq92yolIqACjt7H3sPAcJdiBwo/K7h"
    "PoD/dbnvZ8P7DvAvw4nK+mKLIqgAAAAASUVORK5CYII=")
getpathmanager32Data = pathmanager32.GetData
getpathmanager32Image = pathmanager32.GetImage
getpathmanager32Bitmap = pathmanager32.GetBitmap
getpathmanager32Icon = pathmanager32.GetIcon

#----------------------------------------------------------------------
pathmanager16 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAAN1wAADdcBQiibeAAAAAd0SU1FB9kBHBQxJ6Yyn6UAAAI7"
    "SURBVDjLpZBNSFRhFIafex11roOOzohOZk0MWi6yCMSKJGnlIiIG+wE3TYURRNkPtGjTz6oW"
    "QgQtoh+NFmEiLSJSgtJNEGZWlpaBpjNp6YxOMzr3ep17vxbm1FgDRe/mwPkOz3m+I+3eW3vW"
    "5XKdY0l0XV+oc/rhplu3r5Ei0tGGI2L/voN/fNQ0lZtNN4hEInWtLW13UwJqvbvoH+hPtYSn"
    "nU+Wti63trSdALAAKEoWufa8lADvztqFbZKEJEm03W89DiwAdF1HVWM8fjtD32QWf5UcLxX1"
    "XuGwah8SBn2TWVw5VYOmG4m5ylIHSkYa0zNzvBmJJDGsGWkca+xYYwFQ1RgAX6Y1hiZmAdhS"
    "ls/p5i56el6yTIlT7/MxEIgmAJ4CGwCypmkoSrJ6VVk+nkIbNeuK2V7hITgVpnxlLpWrnb/9"
    "xhKLxRIGAL5tq/BefEB0wo/5bRyrHKfQmUexcpUV2YM41jfS/nr8J2DxBotxZmdizIZY61K4"
    "c/0CIAMRhL8BM/QRV4k12eDXGwD4g7M4ZZUdVdUQOgCkgRpFhIPIFg/Dn8MYhok2byQbpMsm"
    "Arj3zM+huj2Uu+0IM44kl2Cagu7MkwyORXk3GkCNS9htGckGbvscUzM6gZBKIKghyRJudxEi"
    "1I1MMX2jYXqHwwgBAkHcED8BXycn2LC5ilefwvBj4OGLcVw55ykqyOT9yBS9Q2PohoQQsLHU"
    "QcejdvI0f7O01XepM5a+vJp/jG1+9HlX85lN/G++A8ID6G8eMJVAAAAAAElFTkSuQmCC")
getpathmanager16Data = pathmanager16.GetData
getpathmanager16Image = pathmanager16.GetImage
getpathmanager16Bitmap = pathmanager16.GetBitmap
getpathmanager16Icon = pathmanager16.GetIcon

#----------------------------------------------------------------------
pathmanager48 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABHNCSVQICAgIfAhkiAAAClhJ"
    "REFUaIHtmUmIZdd5gL9z7vSGejV0ValaHfXosmRhmXZQEiNsQhxkZDLYC3thG2xnkWljyWCQ"
    "t1oEFEQSiFeKyEKLeBVjjAOKME6sRJEsWcLd0HKLttxTdbWqqmt+w733zFm8Qa+qXlWpBeoQ"
    "6B8O993z7j3n/87/n///z3twV+7KXfl/LWJ3x1NPPRUbY54FPtHvCyHczpguhPDDp59++u+B"
    "23rxg0i8u6Moij+em5v76tmzZ2sA3ntCCCMbgBA718Bay4ULF84++eSTS88888z37zgAUG80"
    "GoyPj7O0tIRzDu/9DpDd98MtjmNOnz5dO3fu3JeAOw/gnLNaa9dqtbh16xbee5xze5QfBdCX"
    "6elpQgif+rCVB5Aj+jpaa5IkIU3TQUuShDiOieOYJEkGrd8XxzFRFBFFEc45gJknnnhi7sMG"
    "GGUBo5QKSina7fZgtftWGF79/azQbrepVqtBa/3W448/fl7K99bJe3+gQlJKnHPvKqW+89xz"
    "z63dNoD3PrfWEscxaZoO9oCUco/79JXZDQJQqVSyarWaTUxMPNpoNAbjCyEGG79/7QMKIZBS"
    "srCw4K5cudIEvnXbANZaY60NSik6nQ7OucHqD18Pi0596XQ6SCmJ43igbF/RKIoGn/v3Ukq0"
    "1pEQYv4w5UcCCCFypZSMoogkSQaDe+8RQhBC2GGNYcX7FhmVN4Zdpz9OCGEHgHOOKIoIIWCt"
    "HftAAM45ba1Fa02n0xn4/+5wOrwnhpXvAwxDDLsN7LTCMMAwiPe++kEBCmOMFEKQpinWWrZN"
    "xk8WZqil7ynV1W//RDtsBLEn3++U3ckQwEZnzn7qrz+7POJh7Yz9xpv//PWXRgJ475UxRpZl"
    "SVEUGGNYadb42MlpvvLYQxTq4CiyR5FDos4BEgM7wnA9i/nPN6/xP+cX/hQYDSClLI0xUkpJ"
    "lmUAOJEye2SMXAUur3QOnTn4wJVrl7ly/Sp5a5sgBIRAvTbGqVOneeD+B5BiVAo6WE7PxQgp"
    "NSHcGKbcIVprJYSIy7Ikz3O01rRVnfuqGW1lKY07cBJVlvz0P15g4sgRZo/eS3LiNAGIhMeo"
    "khuL13nr4gU+9+ifECfJ+1Y+BGgVhlauTJDc6vfvWYbnn3++tNZGUkrSNCWOY6zIqFVTjDvc"
    "Hc6f/wXzDz7I977zVb75+YfZ7Ci2OiXrrZKWhtljxzl+/D4u/Or8+1YeQBlPHEnyXDsZxP4A"
    "AN57q5Sivw9yG1GvJlh7eHW8sbHG1OQUFxfWWVhpUknjQcuSCGUc05OTbG0cmmQHYlzAOE8a"
    "SVq5EkL61f53o6pRAOu9j9M0xRiDJaZeSWjpwy0QfKBeSXnl4k0gcHy2AQSMsWy2SgieJJYE"
    "//6OCt6D0l23TWJBq1BxiOzKgQDee10URaVvAeUE1UrCZlHuebYsCn7x+ssoVQCCIm/xkxf+"
    "bcczQkge+/xjFMqitGatmeODo+IXu6tFAysn9uoRoNBuEKyTSJIXplK/99TAfCMBQggGGFSh"
    "xklqWYK2+Z5nX3/9ZR566EHGJ6cI3tPNDQFCwDnfbcGx0Sq5ud5kq5VzbKJKHDo8UnyTiaOf"
    "RKs2q1slv6w+ixPVwcrn2g7ySRxJjHWAKF966rP2QADnnC6KgqIo6JQGISBLJNbtNHuzuUWS"
    "REzPzNDMFUWpWdnO2W4XdErdBQp9oN7nAD4EEIITH/8ip+cfAgKrSwu0f/k93s6+i3WB0rgd"
    "yTCJBIV2SCGawzqM3MQhBA2QZRlOZIxVYqwP3YmH5N3FBR6YP4U2jqsrTc5dXeXmept2aRhR"
    "DgFQTWO0Kjg+lTPeaIDLwawxc+yTzIWfo4zvus2u95NYUmqDEGFruH8/FyrLsqQsS3IdqNUS"
    "CrU3/m81N/noR+7jlXdW6BR6UFnUsoTxakIUDN713Cr03MooVpdu8pefeYXJuW+DvQ5iDIFn"
    "YnqeaHURxLE9c8VS0MoNINYPBfDea+juAScD9Vo6MoEZbXlnuUWnNIO+qXpG4josv/M2WexI"
    "Y4EU3XpICst0Lefrv/cyf/C5bxEJA9F4782IemOc6soiRbQXIJKCVkeBYGW4fz8LFEoptNYU"
    "OqOapagRAGmlQqcoiKTAuUCWRFSEZm3xEt995MfM3/+7ZGmKFJ5IeKRwjE38FlP3/g2R6IDP"
    "QTbArkP+KjIoJHaERt2Cr1VovA9LhwJ475X3niRJcDIjS1PUiCQ2Oz3L8tYWaXaEwnnqlYTN"
    "5Rv81W+/yBe+8o/EkYfQAw8O7C2wG1C8Cr7oNn0D7BpkH6HV3qaU94wEkAI6ufbWux0V6n4A"
    "uVIKKSXKN0iyBNs9qBMCWB+wztOYOso7ly9xz/xRtLHEUlJ2WszPeeJ0Atw26EVo/QzKSz2Y"
    "XaVz7zbEs2yuvkRbnBkJEIB2rjRBrA737xdGlfeeLMvwskoSx2gTKLXHOj9ILJVqjcnJGVrv"
    "XmFqcpqgNHmnTZRUQWSw8SNovwrREZB9Xx9xOIgarK8us+gfgWh0lRoCtLth6H1t4nZZlj0L"
    "xESRpFkYtN27Dx78+MMsLy2wtbWO94HjJ04ieA3W/gWaPwNZQ8mPcvHiGzvKByljkvoMWaVB"
    "oUpuXHuTt8Sz+N4zux3WOk+no33w7nCAEEI5OJGJlICk1J7Rxahg9uhJZo6eBCChjdH/BOo6"
    "eAtYEIL6WKNbGwDWBbY2Ftm4+RsuxX9BIe5hXX4bG2rsl0C08yhjiES0cSgA0DHGoLVGu4iA"
    "wDqP22d1AKwuyZvr+GIJd78G77oAvk1WvsH9/bNV4xFQC1xtHOO/bjouid+n2phCIPeMPHyn"
    "tKcsXSJDvqOMHQVQK8syACRJgg0CFwR6yPf30G6tUmyvkzfXKJurmJM5yKxbPuDA9PZdVIdT"
    "fwdrP6B5+fssraas2ytUJ2aoTcySVod+iNg1WWk81trs2k+fs0AK6FEANaBhrTXdLOyJBJTO"
    "D3yzP3j/zhmFKgrKokPRaZG325y7mnLyxHXOnPpDhF0C14JgIGoQbjzD+soFLv/6NS68+zWi"
    "sTYiqRIldaK0vmdxAt1t3y4NCOFXr72RAmNAG9DDADGQARXnXCSlNCGqJXEkMAccZEScEVXq"
    "xLokNQrnHD94+49Ya/83n5n/V44cuZepyUmEkGxv32Rz8x/41c0pXrz2ZajMkdYmSKsN4mp9"
    "XwsHoCg0ELaBKmB7FtgBIOgWd9I5l1trWVbj1BuH/75UbRwhq41TGZuiNr6JKtq8WZ7mtXMl"
    "49ESk8k6AkHbTbHpjhFnY2RHx2jUxqk2pkhr44fOsbG2aU1r9SUg6uvZV7ovEmgA4ydOnPjY"
    "8U//+b+rsTNRLCGWhHCbf7YE795roRu+hIwQMkbK6PAfiwgiIEuEtM6HyBm1dOmFv/2z1tKv"
    "l4EW0ATy3aNkdP2rfubhRz9Rmzj2O9ao0FNov4j1oYj1olUYNoSInCm2mrfeevE3QAF0eq0F"
    "+FHLkNDdzBW6QDFd60R3RvU9YgHXu5a91qEXRw6yY0QXoK/8/yWA710Vd+CPw7tyV+7KHZT/"
    "BeS6ZDK6Jlv1AAAAAElFTkSuQmCC")
getpathmanager48Data = pathmanager48.GetData
getpathmanager48Image = pathmanager48.GetImage
getpathmanager48Bitmap = pathmanager48.GetBitmap
getpathmanager48Icon = pathmanager48.GetIcon

